### ISSUE TITLE
odd layout in event pages (was isaw.web #52) 

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.theme#100]
Copying from isaw.web:

I'm discovering some problems in the layout of events (individual event display), now that we're adding new events and including images. The lead image for an event is showing up in an odd place; in the same div with the subtitle, and very small. If we include a caption, it gets even stranger. The caption takes up much more lateral room than the image, and shoves the image over (squishing the subtitle).

When I went looking for the original design spec for event display, I couldn't find the most recent layout - however, I feel like we intended the lead image to show up as the top portlet... above the Event Details block. I could be mis-remembering. In any case, we need to have another look at the styling.

As an example, take a look at this working copy of a new event item:
https://isaw.nyu.edu/events/copy_of_levy-lecture-scythian-burials

**Comment by paregorios** [comment]
Now working on this in branch:issue100

**Comment by paregorios** [comment]
A fix that gets rid of the oddities (though perhaps doesn't create enough beauty) has now been deployed. Final commit on that work was 48453c6a46620a68c4fc676822d11dfe93108624. If we want a more beautiful solution in future, let's open a new ticket for it.
