### ISSUE TITLE
event listing order of fields

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.theme#101]
We need to change the order of appearance of fields in the event listing. Currently, the contents of the subtitle field is displayed below the Speaker name. It should be above the speaker, so that it appears directly below the Title field - and it should be the same color as the title field (making it a link would work).

**Comment by paregorios** [comment]
now in work in branch:issue101

**Comment by paregorios** [comment]
Resolved with a series of commits ending with b2a17b9e42ec87842ae565213dc1598c7199dcdc
