### ISSUE TITLE
event listing - calendar portlet style issue

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.theme#102]
See attached comp; the calendar days when events occur need to be highlighted, rather than just given a bold or different-colored numeral. It's much harder to see which dates have events if they aren't highlighted.
![isaw-09-eventlander](https://cloud.githubusercontent.com/assets/7882896/9914087/2f6e344e-5c7e-11e5-83aa-68b52c85c01e.jpg)

**Comment by paregorios** [comment]
transferred to https://github.com/isawnyu/isaw.web/issues/76
