### ISSUE TITLE
news blog listing doesn't work

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#11]
Notice that news blog listing was not as expected from comps (tiles), even though there was a display setitng for it (and it was chosen). Changed it to standard display. Went to change it back but the option for a news blog view was completely gone at that point.

**Comment by cewing** [comment]
apologies @paregorios, the existing option is still the old view.  I did not get this story finished last iteration.  I will complete the work early this week for you.

**Comment by skleinfeldt** [comment]
Part of Carlos' deployment so marking for review.

**Comment by paregorios** [comment]
closing as resolved, but note now #17 and #20
