### ISSUE TITLE
inconsistent use of color on subheadings

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#15]
A CSS selector in theme.css applies `color: rgba(155,58,37,1)` to all `<a>` elements in `#portal_columns`. Other rules apply a similar color to all `<h3>` elements in several sections of the site, regardless of whether they are wrapped in `<a>` or not. This inconsistency in the application of color is confusing some of our users. 

What would you think about leaving the `<a>` rule as it stands, but removing red from any and all `<h3>` elements in body content?

**Comment by kevintbrooks** [comment]
Agreed - H3 will default to body copy color unless it is a link.
