### ISSUE TITLE
News listing tile problem

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.theme#17]
Some news items (aka blog) have no description and some have long descriptions, which messes up the tile arrangement. Please make CSS adjustments to fix this if possible.

**Comment by kevintbrooks** [comment]
Can you send along a screen shot. Jagged as it is, the grid itself looks to be in working order.

**Comment by cewing** [comment]
@kevintbrooks I'm pretty sure the issue is actually the issue you've identified in #30 

If my work there fixes the problem, we can close this.

**Comment by kevintbrooks** [comment]
Looks good!
