### ISSUE TITLE
theming (CSS?) failure on iphone 6 native browser

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#18]
Examples:

home page:
![img_0352](https://cloud.githubusercontent.com/assets/263285/7986974/637c285c-0aa0-11e5-94b1-ae7c4e4adb9b.PNG)

inner page:
![img_0353](https://cloud.githubusercontent.com/assets/263285/7986984/6e850e1c-0aa0-11e5-9603-7fda75c161bb.PNG)

**Comment by paregorios** [comment]
Chrome on iphone 6 exhibits exactly the same problem.

**Comment by paregorios** [comment]
Same problem on Opera for iphone 6.

**Comment by kevintbrooks** [comment]
FYI this is iPhone only. iPad looks great. Investigating further...

**Comment by kevintbrooks** [comment]
Should have a fix in place here. Let's test after next deploy.

**Comment by kevintbrooks** [comment]
Looks good on my end. @paregorios can you confirm this is fixed?

**Comment by paregorios** [comment]
Confirm. Closing.
