### ISSUE TITLE
events don't show up in full calendar

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#19]
There is currently a test event published on dev. You can see it summarized in the event listing:

![listing-view](https://cloud.githubusercontent.com/assets/263285/7987751/f73322d6-0aa4-11e5-839e-a810fd7e13e8.jpg)

but it doesn't show up on the corresponding day in the full calendar view:

![calendar-view](https://cloud.githubusercontent.com/assets/263285/7987759/076642be-0aa5-11e5-9e50-963ce0417a00.jpg)

**Comment by skleinfeldt** [comment]
@cguardia can you take a look?

**Comment by cguardia** [comment]
The portal calendar tool in the ZMI has a configuration option for setting types that should appear on the calendar. It had almost all types selected, including File, Image and others that of course don't have start and end dates. The ftw calendar code errors out in those cases, so it never showed anything.

Edited type list to use only Events.

**Comment by paregorios** [comment]
Will this ZMI type setting persist into production (i.e., has it been addressed in buildout or policy product or whatever) or is it just something that gets set in the database and therefore will need to be manually adjusted again when we deploy?

**Comment by cguardia** [comment]
Added an upgrade step to take care of this automatically.
