### ISSUE TITLE
navigation portlet first item style

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#2]
Comps show a right-ward pointing triangle edge on the first item in each column of subnavigation options (i.e., on the one corresponding to the current page). Currently on dev we get always-underlined text (which we don't like) and no such triangular edge. 

Here's what we see on dev now:
![dev](https://cloud.githubusercontent.com/assets/263285/7778598/8d9cf426-0092-11e5-9834-dec6139e7fe2.jpg)

Here's what the corresponding comp looks like:
![comp](https://cloud.githubusercontent.com/assets/263285/7778607/9de4e9d8-0092-11e5-8b97-bc92fb530c92.jpg)

**Comment by paregorios** [comment]
This seems to me like a CSS issue. What do you think @kevintbrooks?

**Comment by kevintbrooks** [comment]
Just pushed an update here. Could we put together a few folders with content so we can test how the 'folderish' styling works. 

Also, is there a way to disable that styling on elements that don't have any children. It's odd on pages here to see the arrow indicating more content when there are no children in navigation: http://isaw4-dev.atlantides.org/about/facilities

**Comment by skleinfeldt** [comment]
@alecpm can you answer Kevin's question next week about identifying elements with no children on the nav?

**Comment by paregorios** [comment]
this weirdness may be because of how I set the nav portlet hierarchy settings. Standby.

**Comment by paregorios** [comment]
@kevintbrooks try it now on dev in e.g.the about section. I enabled unlimited folder depth on the nav portlet cc @alecpm @skleinfeldt

**Comment by paregorios** [comment]
@kevintbrooks the update to add the right-hand-end triangular shape looks good, except when our item titles are so ridiculously long that they wrap within the menu element. Consider, for example:

![wrapped-item-dev](https://cloud.githubusercontent.com/assets/263285/7779126/6074dbe4-0097-11e5-9ef0-ffb2eaec0c4d.jpg)

**Comment by alecpm** [comment]
The upward pointing arrow indicates a folder with children, by default folders that aren't the current folder (and its parents) are collapsed.

**Comment by kevintbrooks** [comment]
@paregorios I've updated the menu styling (the up/down arrows were reversed) and increased the line height for wrapped link names. The arrow is supposed to be anchored top right on elements (the comps had menu items with children to illustrate the look). We can take some time with this if you feel the arrow on solo links looks odd.

**Comment by paregorios** [comment]
@kevintbrooks I see. Let's defer messing with this further for the moment. I'll take possession of the ticket and mark defer.
