### ISSUE TITLE
news listing tile images: handle legacy images and cropping

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#20]
Legacy images scale to max-height (I guess), but this oddly traps whitespace where we would expect imagery. Can we do something automatically with CSS to assuage my horror vacui, perhaps use a cropped version, if available, of the associated news item image? The cropping plugin seems to work on these, but the news listing ignores them.

**Comment by skleinfeldt** [comment]
Let's discuss in standup whether we can do anything about the scale/crop (first) issue in Plone.

**Comment by paregorios** [comment]
reassigned to @cewing after splitting off the css bit into a new ticket, as discussed in today's standup.

**Comment by skleinfeldt** [comment]
Re-re-assigning to @alecpm who is doing the tickets this week.

**Comment by paregorios** [comment]
We might need a brief confer on this one @alecpm @kevintbrooks @skleinfeldt in order to determine whether there's a css thing that can/should be done or whether this requires more templatey/pythonical intervention. Assigning to "pre-deploy" for the purposes of that discussion, after which we'll determine whether to implement now or later (though I feel like something needs to be done in advance, at least at the moment).
