### ISSUE TITLE
header contents on very narrow devices

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#21]
Using screenfly, I've noticed that pre-programmed devices with widths less than about 320px (e.g., Motorola RAZR V3M and V8 (240px and 176px, respectively), the NYU logo is too wide and collides with the menu button. Can we use CSS to hide the NYU logo entirely at widths below 320px? Or can we substitute a narrower alternative image?

**Comment by kevintbrooks** [comment]
Done!
