### ISSUE TITLE
home page slider: crossfade transition does not work

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#22]
When the transition is changed from "slide" to "crossfade" through the web, The first image is displayed all the time (there's a brief transition to gray). The second overlay appears on time, but we never see the second image.

**Comment by paregorios** [comment]
Plain "fade" does work fwiw.

**Comment by skleinfeldt** [comment]
@cguardia can you take a look?

**Comment by paregorios** [comment]
plain fade is fine
