### ISSUE TITLE
legacy event types are still hanging around in action menu

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#24]
Does this mean that we didn't migrate legacy events to new events on the last round of deployments? Or will these add options linger until something is either added to the events upgrade process, policy product, or done manually via the ZMI? I'd really like these to be gone once and for all when we deploy to production; I thought that's what we were after with the closed event migration stories.

**Comment by skleinfeldt** [comment]
Hopefully the events were migrated but the old content type was never removed. @alecpm can you take a look?

**Comment by cguardia** [comment]
Removed the isaw.events product from the buildout. The migration had been done, but the old types still were available because they were installed.
