### ISSUE TITLE
font weight looks too heavy in IE 11

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.theme#25]
Looking at the home page in IE 11, the fonts look heavier. It's particularly noticeable in the four primary top navigation tabs.

**Comment by kevintbrooks** [comment]
Looks like normal IE behavior, unfortunately. DirectWrite tends to be a little heavier on Windows than Chrome (which still uses ClearType). Hoefler & Co, who serves Gotham, actually serves custom font files for different browser/engine combinations.

Marking this as closed, but if you see anything really off, let me know.
