### ISSUE TITLE
in news listing tile view: handling absence of lead image on a news item

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#26]
The default behavior in these tiles for news items without a news image is, it appears, to provide a default image. Could we instead just use a generic band of color? Many of our users (esp. internal decision makers) will not be happy with an "unrelated" image appearing on a news item. Alternatively, we could look for an image that's associated with ISAW's identity, e.g., part of the front of the building or something like that

**Comment by kevintbrooks** [comment]
What about a simple placeholder like this?

![placeholder](https://cloud.githubusercontent.com/assets/1392386/7992116/f865f2a2-0aca-11e5-9378-a2a9cabb3702.png)

**Comment by paregorios** [comment]
Yes, let's use that for now.

**Comment by kevintbrooks** [comment]
@skleinfeldt could you assign this to the appropriate party for implementation?

**Comment by skleinfeldt** [comment]
Assigning to @alecpm

**Comment by alecpm** [comment]
This should be fixed on staging.
