### ISSUE TITLE
item titles are repeated

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#3]
There seem to be a number of places on dev where we see what users will think of as the "page heading" appearing twice; once in the color-washed photo banner immediately below the header and then again in the main content section. Some of the places where I see this include (not exhaustive):
- /about 
- /library 
- /news
- /support-isaw

Here's an example:

![news-dev](https://cloud.githubusercontent.com/assets/263285/7778994/2a627ecc-0096-11e5-9765-fc7298600378.jpg)

We get a similar layout, but with different content on (e.g.) /publications, /research, /graduate-studies, /visiting-scholars, exhibitions.

It doesn't occur on /events, /people/faculty.

I think the difference is between a plain folder view and a folder in which a default content item has been selected as the display.

Comps have led our users to expect a less repetitive appearance, for example:

![news-comp](https://cloud.githubusercontent.com/assets/263285/7778963/dcfb8fc0-0095-11e5-8950-3ed9e2a75552.jpg)

How do you think we should try to make this more cohesive?

**Comment by paregorios** [comment]
Not sure to whom to assign this one ... thoughts @skleinfeldt ?

**Comment by skleinfeldt** [comment]
@alecpm will probably take it, but there is no need for you to assign each ticket - we'll meet and decide how to divvy up tickets on Tuesday.

**Comment by paregorios** [comment]
ok, I’ll stop bugging you about it

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
Just for explanatory purposes, the title in the header is the "section" title, which is generally different from the page title.  However if you are on the homepage of a top level folder (and that homepage has the same title as the section folder), then you will see that title twice.  We can attempt to automate hiding the page title under those circumstances using XSLT rules or a customized title macro, or provide custom view(s) which hide the title which can be selected manually for such pages.

**Comment by skleinfeldt** [comment]
@paregorios please give us some guidance on what to do here??? Then @alecpm will proceed.

**Comment by skleinfeldt** [comment]
@paregorios I think this was resolved by the design changes you and Kevin decided on, that are now deployed? So marking reviewing.

**Comment by paregorios** [comment]
yes. this is fixed.
