### ISSUE TITLE
News Item Paging Grid Error

### ISSUE THREAD

**Issue by kevintbrooks** [isawnyu/isaw.theme#30]
The `<div data-nextpage="3" style="display:none;"></div>` element is causing issues with the grid when new pages are loaded via ajax.

**Comment by cewing** [comment]
Fixed, ready for review in next release.

@paregorios, please confirm that after this work is deployed the news listing grid works as expected (in terms of layout) and then you can close this and #17

**Comment by paregorios** [comment]
Beautiful!
