### ISSUE TITLE
footer scroll behavior for logged-in users

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#31]
Once you're logged in and all those extra portal actions get festooned into the list in the bottom right portion of the footer, the footer gets bigger than its box and you Have. To. Scroll. Any chance we can do something more elegant and especially less frustrating for the user?

**Comment by kevintbrooks** [comment]
Updated CSS.

**Comment by skleinfeldt** [comment]
Assigned to @paregorios to review and close (just want to make sure he approves the change.)

**Comment by paregorios** [comment]
This does not appear to me to be fixed. I still have to scroll in the footer when I am logged in. Reassigning to @kevintbrooks .

**Comment by kevintbrooks** [comment]
Looks like this is waiting on a deployment.
