### ISSUE TITLE
maddening amounts of internal whitespace at bottom of rich text boxes in edit view

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#33]
We've been living with this for a long time on production; I was hoping it would magically go away with upgrade and new theme, but it's still very much with us. Wouldn't be so bad if the body richtext box were the last field on the edit form (it's not always), and if the save button was at the top of the form instead of the bottom. As it is, you sometimes have a marathon scroll. 

Behold:

![death-by-scroll1](https://cloud.githubusercontent.com/assets/263285/7993966/900224ec-0acf-11e5-85e2-4b9642265b68.jpg)

wait, wait, there's more:

![death-by-scroll2](https://cloud.githubusercontent.com/assets/263285/7993972/99b462a2-0acf-11e5-9581-84e2aec6d045.jpg)

And, no, there are not any blank lines following the line "etc. and so forth"

**Comment by cewing** [comment]
it is absurdly awesome.

**Comment by skleinfeldt** [comment]
It's so absurdly maddeningly awesomely awful I don't know who to assign this to.

**Comment by paregorios** [comment]
this may be a chrome bug

**Comment by k2soule** [comment]
not just chrome; I have observed this in Safari and Firefox as well

**Comment by k2soule** [comment]
Also, as Roger pointed out today, there is the problem of the editing window being located incorrectly in the browser window; such that the right side of the content is off-screen, and one has to scroll to the bottom of the page to get another scroll bar to move the editing window into view... Is this related? Or should it be a separate ticket?

**Comment by paregorios** [comment]
I think it warrants a separate ticket, but with a cross reference link.

**Comment by paregorios** [comment]
transferred to https://github.com/isawnyu/isaw.web/issues/88

**Comment by paregorios** [comment]
Reopening. @k2soule can you take on making a new ticket in the isaw.web tracker for the problem noticed by @rogerbagnall that you commented on above? Thanks.

**Comment by k2soule** [comment]
created a new ticket in isaw.web for the horizontal alignment issue. closing this ticket.
