### ISSUE TITLE
Override byline and make visible on content items.

### ISSUE THREAD

**Issue by cewing** [isawnyu/isaw.theme#34]
Should appear on all non-container items?

**Comment by cewing** [comment]
Overriding the date format is finished, upgrade step 13 for isaw.policy.

**Comment by cewing** [comment]
Fixed.  We have a customized version of the byline viewlet that will appear on all text-based content types.  (this prevents it from appearing on folders and collections, where it's not likely to be of any use).

**Comment by cewing** [comment]
When deployed, this is ready for your review, @paregorios, so I'm assigning to you.

**Comment by paregorios** [comment]
This is complete. Will open new issue for suppression of byline display on select content items.
