### ISSUE TITLE
rsvp functionality on events is not implemented properly

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#40]
Three aspects to this problem:
1. The "register now" buttonish thing in the right-hand portlet should only appear when the "rsvp required" field on the individual event is True. Right now it appears always.
2. The text for the "register now" button should read "RSVP required".
3. The register now button should be a hyperlink to /rsvp.

I've marked this as a "bug" and put it in pre-deploy because right now we have an affordance on the interface that does nothing and that doesn't correspond to actual data, which will drive users nuts.

**Comment by paregorios** [comment]
This is not the same as #57, but is related in that it depends on the same boolean value in the event content type.

**Comment by cguardia** [comment]
Fixed.
