### ISSUE TITLE
calendar buttons and grid need tweaks

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.theme#46]
In calendar view, the Month and Week buttons look unfinished (missing a side border), and the calendar grid is misaligned in Week view.

**Comment by skleinfeldt** [comment]
@k2soule should this ticket be in the pre-deployment milestone?

If not (if it is to be fixed post-deployment), can you make a copy in the isaw.web repo and close this one "wontfix"?

**Comment by k2soule** [comment]
I think this may be fixed, but I can't tell at the moment (can't see events). I'll make a copy in iaw.web, to remind myself to check.

**Comment by k2soule** [comment]
Re-created as isaw.web issue #37. Closing this version as "wontfix".
