### ISSUE TITLE
Implement Scrumdo Story 38

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.theme#47]
Theme profile item: https://www.scrumdo.com/projects/project/isaw/iteration/128081# (see attachment for comp)

**Comment by k2soule** [comment]
examples of profiles with lots of fields filled out: 
http://isaw4-dev.atlantides.org/people/faculty/roger-bagnall
http://isaw4-dev.atlantides.org/people/faculty/sebastian-heath

example of a profile with minimal fields filled out: 
http://isaw4-dev.atlantides.org/people/staff/desiree-carrasquillo

**Comment by alecpm** [comment]
This is implemented (along with a little bit of styling to sort of match the comps):

http://isaw4-dev.atlantides.org/people/faculty/roger-bagnall

Assigning to @kevintbrooks  for any refinements needed.

**Comment by kevintbrooks** [comment]
Made a few updates here - assigning to @paregorios for review.
