### ISSUE TITLE
byline appears on homepage

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#50]
I think it's covered up when viewing in a wide browser, but when you get narrow enough to trigger menu collapse and so forth for mobile/tablet, you can see it. I assume (hope?) that this will get magically fixed when #42 is resolved.

![byline-home-narrow](https://cloud.githubusercontent.com/assets/263285/8074288/a59f921a-0ef5-11e5-8d4d-86f4a32b130e.jpg)

**Comment by skleinfeldt** [comment]
@paregorios did #42 resolve this?

**Comment by paregorios** [comment]
Yes! Closing.
