### ISSUE TITLE
RSVP indications not appearing in events listing view

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#57]
The comps (see attachment to scrumdo story 41) show an "RSVP" box on individual event summaries appearing in the events listing view. These are meant to appear conditionally: show box when the corresponding event:rsvp field is True; don't show box when it is false. Right now per @kevintbrooks there is no HTML appearing at all in the event listing.

**Comment by paregorios** [comment]
This is not the same as #40, but is related in that it depends on the same boolean value in the event content type.

**Comment by alecpm** [comment]
This should be fixed on staging.

**Comment by paregorios** [comment]
I'm not seeing RSVP-related HTML in source or visual in the events listing for the one event that has RSVP=yes. What am I missing?
![rsvpwha](https://cloud.githubusercontent.com/assets/263285/8577138/4e4726e4-256c-11e5-9082-9fd140a2b555.jpg)

**Comment by alecpm** [comment]
Looking into this, it's super confusing since it's working perfectly on my dev machine.  I suspect there may be a ZODB customization lurking somewhere.

**Comment by alecpm** [comment]
This is fixed now.
