### ISSUE TITLE
drop-downs for style and font-size do not display

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#6]
On dev, when editing a rich text field on a content item, one clicks the combo box (drop-down menu) for Style or Font Size, but the selectable portion of the menu never appears.

**Comment by alecpm** [comment]
While working on #12, I ran into this issue.  Unfortunately, it appears to be a bug in the TinyMCE js, which is setting the menu positioning as if it were attached to the rich text field element as opposed to fixed at the top of the window.  Upgrading Products.TinyMCE to 1.4.2 does not resolve the issue, and the issue appears to affect ISAW production as well.

**Comment by paregorios** [comment]
Do you think it will work to stop pinning the editor menus to top of window and go back to the clearly more-widely used default of pinning it to the rich text field element?

**Comment by alecpm** [comment]
Yes, that will fix the issue, though you'll also want to change (or unset) the toolbar width, which currently set assuming an external toolbar.

**Comment by paregorios** [comment]
I've addressed this on staging, thanks. Will close won'tfix.
