### ISSUE TITLE
need repeatable method to change CSS registry on staging

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#62]
In order to demonstrate to stakeholders font alternatives, I need a more-or-less on-demand way to make changes to the CSS registry configuration in an iterative fashion until we settle on a font combination. I understand from email that such changes should be done "preferably with an upgrade step". I need guidance on how to do this.

**Comment by alecpm** [comment]
The specific issue here is that your change (46d0441d7cb2fb7260c1cfa6051c800fea451368) removed fonts.css from the theme, but that file was also being included in the Resource Registry: https://isaw4-dev.atlantides.org/portal_css/manage_cssForm

I've disabled that file there now, and it is no longer in the profile (it's a bit of a mystery to me why it was still enabled in the registry, given that it isn't in the profile).  Going forward your changes to the theme (either via additional <link> elements or changes to the theme.css) should be all that's needed to update fonts.
