### ISSUE TITLE
css: address margin/padding for missing images in people pages

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#63]

**Comment by paregorios** [comment]
This is still an issue (see) below, and presumably only requires a minor CSS tweak, which I'll undertake.

![peeps](https://cloud.githubusercontent.com/assets/263285/9114258/7685415e-3c1e-11e5-890b-c5fc3fef3790.jpg)

**Comment by alecpm** [comment]
I've committed a fix; not sure it's what you want though:

http://isaw4-dev.atlantides.org/people/staff

**Comment by paregorios** [comment]
Not ready to close this, but I don't think it needs to be addressed ahead of rollout. Punting to backlog for now.

**Comment by paregorios** [comment]
transferred to https://github.com/isawnyu/isaw.web/issues/89
