### ISSUE TITLE
New Snapshot

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.theme#68]
Copy over a new prod snapshot to staging and run all upgrade steps

**Comment by cguardia** [comment]
I copied the snapshots and ran the upgrade steps. I had some problems getting the site to display, but it's there now. It looks like we will have some work to do to get it looking like before.

**Comment by paregorios** [comment]
My first impression is that stuff we agreed I’d set up through the ZMI and that then would get replicated in code either didn’t get done or the associated upgrade steps didn’t get run. But that’s just a guess. Anyway, we’ll probably need to attempt to fix then try to do the switchover dry run again from scratch.

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by skleinfeldt** [comment]
Yes, documenting what we do like crazy....

**Comment by skleinfeldt** [comment]
Ticket #74 opened for fixing and documenting, @paregorios can we close this one?

Also if you have a list of the steps you set up in the ZMI and were expecting to be implemented in code, please add them to #74.

**Comment by k2soule** [comment]
Assigning to Tom. Looks like this issue can be closed, but the process will be detailed and repeated in #74.
