### ISSUE TITLE
site id string is hard-wired instead of supplied from the plone

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#69]
There's a site ID string appearing in the text node of the `<h1>` on the home page that does not match the site ID string assigned through the control panel settings ("Institute for the Study of the Ancient World"). Instead, it matches a string found in the comps, and it's wrong ("Institute for the Study of the Ancient World at NYU"). 

It's not currently visible because of CSS fanciness, but I'd like to rip that out and actually use the text.

Presumably this is in the theme package somewhere? Can someone give me a pointer to what to change?

**Comment by skleinfeldt** [comment]
From Alec on Skype: It's part of the theme templates: https://github.com/isawnyu/isaw.theme/blob/master/isaw/theme/static/index.html https://github.com/isawnyu/isaw.theme/blob/master/isaw/theme/static/home.html

**Comment by skleinfeldt** [comment]
And: Making it dynamic would mean updating the rules.xml to replace the text from the theme with the text from the headers here: https://github.com/isawnyu/isaw.theme/blob/master/isaw/theme/static/rules.xml#L61

**Comment by alecpm** [comment]
This is fixed in the theme.

**Comment by paregorios** [comment]
Thanks. Looks good to me.
