### ISSUE TITLE
Fix snapshot and document

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.theme#74]
The snapshot made on 8/3 had some problems when the new theme was applied. Fix the problems and document all the steps in isaw.web/THEME-UPGRADE.txt (currently has an obscure name, PROD_SNAPSHOT.txt.)

Anything that can be automated via an upgrade step should be.

**Comment by paregorios** [comment]
I was asked to detail ZMI steps that I'd like to see replicated in code here. I can't remember precisely the discussion; I see no evidence that it was documented, and I may have dropped the ball on communicating back what was done. But the major issues were around creating the primary nav and footer links. The main nav tabs should be as follows:
- Graduate program
- Visiting Research Scholars
- Events
- Exhibitions

There are other open tickets for the footer items.

**Comment by paregorios** [comment]
Note that we seem to have a regression on #66 in staging.

**Comment by paregorios** [comment]
Some other items to possibly automate:
- disable globally the legacy isaw featured portlet
- enable globally subnavigation in left portlet slot, except for the following sections:
  - /events
  - /exhibitions
  - /research

**Comment by alecpm** [comment]
All top level folders will need to be set exclude from nav, excepting for the following:
- events
- exhibitions
- visiting-scholar-program
- graduate-studies

Rename the following:
- visiting-scholar-program: visiting-scholars: Visiting Scholars
- graduate-program: graduate-studies: Graduate Studies

**Comment by paregorios** [comment]
Until the nav is cleaned up, (extra tabs removed) I won't be able to check default view settings etc. on things because the relevant UI affordance is overlapped by the extra tabs.

**Comment by paregorios** [comment]
Can we get a status update on this?

**Comment by paregorios** [comment]
I have done the "exclude from nav" and rename steps on staging recommended by @alecpm above, which has cleared my block for testing other fixes; however, there is still one problem with the main nav tabs, and I've made a comment to that effect on #77 .

**Comment by skleinfeldt** [comment]
#77 has been closed, that problem was fixed (in code). There was a second problem that surfaced on #66, but @alecpm is fixing that now.

I wanted to capture here that left nav was missing on staging as of 1:00 ET, needs to be fixed (portal setting - disable from right, enable on left), and that step needs to be added to the doc.
