### ISSUE TITLE
Bring back main navigation

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.theme#77]
Something seemed to stomp this on local dev environments.

**Comment by alecpm** [comment]
It's back, should be permanent.  Will need to rename and exclude from nav a few items.

**Comment by paregorios** [comment]
What should I update locally on my dev to get the resulting effect?

**Comment by paregorios** [comment]
Have gone through steps to rename folders and to exclude other from navigation on dev. One problem remains: two "Graduate Studies" tabs.

**Comment by alecpm** [comment]
There was a portal action for that tab, it is gone on dev and I'll ensure it's removed in an upgrade step.

**Comment by paregorios** [comment]
Great, thanks.

**Comment by alecpm** [comment]
It's in an upgrade step now.
