### ISSUE TITLE
content actions drop-downs are z-stacked beneath the footer

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#79]
Needs CSS fix. 

![zfooter](https://cloud.githubusercontent.com/assets/263285/9113963/f33c6aa8-3c1c-11e5-8075-70bc5b58a918.jpg)

**Comment by skleinfeldt** [comment]
@paregorios needs to hand this over to you @alecpm

**Comment by alecpm** [comment]
Looks like this isn't really a z-index issue, but an issue with the HTML structure and positioning.  I've added a min-height to the content body (#portal-columns) for logged in users to ensure this doesn't happen.

**Comment by paregorios** [comment]
confirmed.
