### ISSUE TITLE
coping with giant titles in page headings and breadcrumbs

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#8]
Given our propensity for very long titles (especially for events), the current all-caps, all-the-time style for main headings is problematic (note also what happens to breadcrumbs). Any ideas (other than not using long titles, which is not an option) about what we can do in this regard? See, for example:

![giant-titles-events](https://cloud.githubusercontent.com/assets/263285/7796578/3c2ffb9a-02a6-11e5-84fd-0cb6833e2324.jpg)

**Comment by paregorios** [comment]
NB: on the current site we have a solution for breadcrumbs: custom code that truncates what's displayed at the first colon (if there is one, which in these long titles, there often is).

**Comment by kevintbrooks** [comment]
@paregorios I like the idea of breaking breadcrumbs at the colon to keep those under control.

For long titles like this, would it be possilbe / advisable to break this up into a title and a subtitle field? Whether obvious to the user or done automatically at the colon?

**Comment by paregorios** [comment]
@skleinfeldt @alecpm what's harder and more time-consuming, do you think? Writing custom code to truncate/split titles and breadcrumbs on colons, or adding subtitle field to the "event" type? Or has someone by chance written a super-cool product that does for subtitles what "lead image" does for images?

**Comment by alecpm** [comment]
I think it probably makes sense to do this in JS.  Splitting the heading on the semi-colon into title/subtitle and truncating the breadcrumb on the semi-colon and/or a set number of characters. @cewing any thoughts on this?

**Comment by cewing** [comment]
What does "subtitle" mean in terms of the site theme?  Is it the larger font that we had previously though would be the first paragraph of body text?  If so, do we need to watch out for and deal with cases where the title gets split into title/subtitle and suppress that first paragraph display?  And do we do this for any title that contains a colon?  Only for those on events?  What happens if the title contains a colon but is short?  (I know, _academia_, unlikely, but still possible).

If we can come up with a full understanding of this and how it interacts with other parts of the page, then yeah, I think we can certainly do it in javascript.  That would save any special Python coding or adapters, the editors/authors could continue to behave as they always have and things would "just work"™

**Comment by kevintbrooks** [comment]
As far as styling, we'd likely come up with some CSS for this new element
to differentiate between a subtitle and an introductory piece of content.

**Comment by paregorios** [comment]
Ah, if only it were easy to search the ZODB via the portal catalog for all titles containing a colon. I tried playing around with the ZMI to do this, but no luck. I guess one has to write Python? @alecpm or @cewing can you advise?

**Comment by skleinfeldt** [comment]
@alecpm it is clear what needs to happen here? Is the JS task some you would do or @kevintbrooks ?

**Comment by alecpm** [comment]
I can do the JS.  My initial thought is to split on a ':' for both the main title and the breadcrumb.  For the main page title, we'd add a "p.sub-title" below the title tag containing the part after the colon.  For the breadcrumbs we'd just truncate (perhaps also have a word or character limit for truncating long titles with or without colons there).  Not sure what to do in listings/search though.

**Comment by paregorios** [comment]
+1 on @alecpm's ideas, including the length limit for truncation, which in my view should only truncate on word breaks. My instinct is to leave listings/search alone for now; we're backing away from some of the all caps usage around the site, and it will look less crazy if we go that direction on search, but I want to see it before pushing for a CSS change.

**Comment by paregorios** [comment]
Right, so the remaining issue here is truncation in breadcrumbs and <br/> insertion (or similar) in headings?

**Comment by paregorios** [comment]
Put this on the backlog because it's not job one at the moment.

**Comment by paregorios** [comment]
transferred to https://github.com/isawnyu/isaw.web/issues/67
