### ISSUE TITLE
fix horizontal alignment of breadcrumbs in new theme

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#80]
CSS tweak.

**Comment by skleinfeldt** [comment]
@paregorios needs to hand this over to you @alecpm

**Comment by alecpm** [comment]
I going to assume you want them aligned with the site title unless I hear otherwise.  The mockups have them in an entirely different location, so I'm not quite sure.

**Comment by paregorios** [comment]
Yes please align with the site title.

**Comment by alecpm** [comment]
Should be fixed

**Comment by paregorios** [comment]
confirmed.
