### ISSUE TITLE
replace SVG title with text in header

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#81]
CSS tweak.

**Comment by skleinfeldt** [comment]
@paregorios needs to hand this over to you @alecpm

**Comment by alecpm** [comment]
I'm not sure I understand what's desired here.  Is this in reference to the ISAW logo.  Currently there's text markup:

```
<a href="/">ISAW</a>
```

It's replaced via CSS with an SVG image background and a text-indent.  Do we want to replicate the SVG in pure html/css?

**Comment by paregorios** [comment]
Let's defer this ticket for now.

**Comment by paregorios** [comment]
relocated to https://github.com/isawnyu/isaw.web/issues/86
