### ISSUE TITLE
slider fails to display content (imagery) on home page

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#84]
On first request to page. Must refresh to get slider content. Have verified on Mac in chrome, FF, safari.

**Comment by paregorios** [comment]
This is a blocker for senior staff review ahead of rollout approval.

**Comment by alecpm** [comment]
Should be fixed now.

**Comment by k2soule** [comment]
I just checked from Safari and Firefox; I agree the sliding images are back; however, I see a horizontal scroll bar at the bottom (in both browsers).

**Comment by alecpm** [comment]
OK, I think I have this nailed down.  There were two causes, a race condition on the slider image loading (browsers all implement load events a little differently depending on whether images are coming out of the cache or not) and an issue for logged in users where the edit bar was stretching the body width 6px past 100%.

**Comment by k2soule** [comment]
Thanks for tracking that down. The scroll bar is no longer there, from what I can see (Firefox in Win7, Firefox and Safari in MacOS).
