### ISSUE TITLE
Tag code going to production

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.theme#87]
Just before we do the upgrade, so we know what we deployed.

**Comment by paregorios** [comment]
Is this done? Can we close?

**Comment by cguardia** [comment]
There is already a tag production08112015 for the code as it was when we deployed. There have been a couple of fixes, though, and there might be more.

**Comment by paregorios** [comment]
relocated to https://github.com/isawnyu/isaw.web/issues/85
