### ISSUE TITLE
Heading styles inconsistent on faculty page

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.theme#88]
See http://isaw4-dev.atlantides.org/isaw/people/faculty/roger-bagnall - the A. B. C. etc headings are sometimes in gold, sometimes not. Firefox 39.

Putting in pre-deploy milestone for @paregorios to assess.

**Comment by alecpm** [comment]
A note on this one:

h2 headers are treated as section heading and given those gold bars with letter ordering, other headings are styled as on other parts of the site.

**Comment by skleinfeldt** [comment]
So in other words A, B, C, D, E, F are H2, then A, B, C, D, E, F that are under F are H3, then we go back up a level to G an H2. I missed that, on scanning I just saw F and G adjacent at the bottom in different styles but same indent.

So this in not a styling bug, it is a somewhat confusing template. (I'd suggest removing the letters from those subheadings.) Moving to "backlog" milestone for @paregorios to ignore or move somewhere else.

**Comment by paregorios** [comment]
transferred to https://github.com/isawnyu/isaw.web/issues/84
