### ISSUE TITLE
home page slider images cut off at the top

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.theme#93]
A slice of about 165 pixels is cut off from the top of each image in the home page slider. The images we're using are all 1920x1280. When authenticated, I can see part of the missing slice of image above the green editing bar, though not all of it.

I tested adding a shorter-cropped image to the slider, and it still appears to cut off the same amount from the top. Perhaps the top of the image is hiding underneath the header?

**Comment by paregorios** [comment]
Now working on this in branch issue93

**Comment by paregorios** [comment]
functionality at e7a7044

**Comment by paregorios** [comment]
resolved and deployed to production
