### ISSUE TITLE
website title font wrapping is rotten in IE11

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#94]
![font substitution issue in ie11](https://cloud.githubusercontent.com/assets/263285/9543935/7b8675e4-4d42-11e5-8dfe-f1f42380ed75.jpg)

fyi @k2soule

**Comment by k2soule** [comment]
Not just the wrapping, but the header fonts themselves are incorrect - and the ISAW logo graphic is not displaying well.

**Comment by paregorios** [comment]
We may have to get rid of Questrial entirely

**Comment by paregorios** [comment]
transverred to https://github.com/isawnyu/isaw.web/issues/80
